### ISSUE TITLE
cant connect to SQL

### ISSUE THREAD

**Issue by BladeFireLight** [fvanroie/DscDashboard#3]
I get the error
Unable to connect to the SQL Database. Please check the DSC_SQL environment variable or DscDashboard DSN.

I have the same connection string used by DSC in $env:DSC_SQL but I still get the above error.

trying to pick apart the underlying commands I get this. 

Get-ODBCData -ConnectionString $DscConnectionString -query "Select TOP 1 * from Devices;"
Exception calling "Open" with "0" argument(s): "ERROR [IM002] [Microsoft][ODBC Driver Manager] Data source name not
found and no default driver specified"
At C:\Program Files\WindowsPowerShell\Modules\DscDashboard\0.0.2\Public\Get-ODBCData.ps1:48 char:9
+         $conn.open()

**Comment by fvanroie** [comment]
Please try to create a system DSN called 'DscDashboard' that connects to your SQL server using control panel ODBC Data Sources. Then leave the $env:DSC_SQL empty.

**Comment by BladeFireLight** [comment]
windows PowerShell on server 2016 core. connecting to SQL 2017 default instance on another server. 

Do you have an example connection string?

**Comment by fvanroie** [comment]
OK, so I tested the script on Windows 2016 Core. It's currently expecting an ODBC DSN named DscDashboard with the Driver and Database parameters... I'll eliminate this in the next update, but for now you'll need to add a System DSN like this:
```
Add-OdbcDsn DscDashboard -DsnType System -Driver "SQL Server" -Platform 64-bit -SetProp "Database=DSC"
```
To verify it is connecting, you can run:
```
//Dot source Get-ODBCData script
. C:\Program Files\WindowsPowerShell\Modules\DscDashboard\0.0.2\Public\Get-ODBCData.ps1

//Run a Test Query
Get-ODBCData "select * from devices" -Conn "DSN=DscDashboard; SERVER=hostname; UID=user; PWD=pass;"
```
If that doesn't give you any errors, set the environment variable:
```
$env:DSC_SQL = "SERVER=hostname; UID=username; PWD=password;"

//Run a Test Query without the ConnectionString
Get-ODBCData "select * from devices"
```

Hope this helps.

**Comment by BladeFireLight** [comment]
I'm not getting connected. 
PS C:\> Get-ODBCData "select * from devices" -Conn "DSN=DscDashboard; SERVER=sql01; UID=contoso\dscsql; PWD=Lizard123;"
Exception calling "Open" with "0" argument(s): "ERROR [28000] [Microsoft][ODBC SQL Server Driver][SQL Server]Login
failed for user 'contoso\dscsql'.
ERROR [28000] [Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user 'contoso\dscsql'."
At C:\Program Files\WindowsPowerShell\Modules\DscDashboard\0.0.2\Public\Get-ODBCData.ps1:48 char:9
+         $conn.open()
+         ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : OdbcException

**Comment by fvanroie** [comment]
```
Login failed for user 'contoso\dscsql
```
This error means indicates an issue with authentication. Please check the credentials or try to use a SQL integrated account.

**Comment by BladeFireLight** [comment]
what permissions are required? I can only get that step to work with the SA. and I cant use that in production.

**Comment by BladeFireLight** [comment]
looks like I got it working
I set $env:DSC_SQL to "DSC_SQL", "SERVER=sql01; Integrated Security=true; Trusted_Connection=yes;"

**Comment by NikosBal** [comment]
I am receiving the same error, I have enabled whireshark monitoring  and I didn't find any data exchanged with SQL server, I have modified   dashboard.ps1 and found that a System.Management.Automation.MethodInvocationException  while Try Get-ODBCData -ConnectionString $DscConnectionString -query "Select TOP 1 * from Devices;" 

Running manually dashboard.ps1 works passes the try catch
