### ISSUE TITLE
InstallDscDashboard.ps1 - issue with configuration

### ISSUE THREAD

**Issue by jpomfret** [fvanroie/DscDashboard#6]
Not sure if you want me to create a PR for this, but I think the variable name on this line is incorrect. Should be `$dotnetInstaller`, when I changed that locally and reran it my configuration worked and my dashboard is up and running 😍

https://github.com/fvanroie/DscDashboard/blob/189a014f5163d371da5e990bff5af877e90fb04c/docs/InstallDscDashboard.ps1#L40

**Comment by fvanroie** [comment]
Nice catch @jpomfret. No need for a PR, I updated the InstallDscDashboard.ps1 script with the fix.
Thank you for reporting this issue!
